SWM-Space-Odyssey/WeddingMate_BackEnd

- .idea/workspace.xml
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/CategoryEnum.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioTagMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/PortfolioTag.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/dto/TagMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/CustomerSignupReqDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/PlannerSignupReqDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customer.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/PlannerTag.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/CustomerMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/PlannerMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/PlannerTagMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/CustomerRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/PlannerRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/PlannerTagRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/UsersRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
- src/main/resources/application-dev.yml
OAuth2로 User 객체 생성 후 플래너, 예비부부별로 추가 정보를 받아 회원가입하는 기능 구현
- Planner, Customer는 User를 상속받지 않고 @OneToOne 조인 방식으로 구현
- Planner의 경우 plannerTag 사용
- Customer의 경우 portfolioTag, plannerTag 사용
- portfolioTag에 customer 관련 의존성 추가
- 원래는 상속을 이용해서 single table이나 joined 방식으로 구현하려 했으나, 상속을 이용하려면 User entity를 추상 클래스로 정의해야 함. 하지만 현재 구현 방식은 OAuth2 구현 후 User 객체를 생성하여 db에 저장해야 하기 때문에 User를 일반 클래스로 정의하고 Planner와 Customer와 1:1 매핑하는 방식을 사용
- 현재 무슨 이유에서인지 영속성 컨텍스트가 작동하지 않는 것 같음 -> 해결(https://github.com/SWM-Space-Odyssey/WeddingMate_BackEnd/discussions/33)
> [SO-52] feat: 플래너, 예비부부 회원가입 api 추가

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
- 새로 구입한 도메인으로 redirect 주소 변경
1. 프론트 도메인 주소와 백엔드 도메인 주소가 달라 중간 과정에서 쿠키가 막힘
2. 공통 도메인을 사용하는 것으로 변경(FE: weddingmate.co.kr, BE: api.weddingmate.co.kr)
1. 추후 FE와 BE 도메인 둘 다 https 연결을 위한 설정이 필요합니다. 현재 ssl 인증을 위한 acm 인증서 발급 요청을 해놓은 상태입니다.
> [SO-143] feat :  도메인 적용 및 redirect 주소 변경

- .github/workflows/deploy.yml
- config/scripts/delete.sh
- config/scripts/deploy.sh
- ec2 내의 용량 부족 문제로 deploy 시 오류 발생
- 사용하지 않는 Docker image & container 삭제 script 추가
- 추후 CD로직 추가 및 이미지 백업을 위해 AWS ECR에 이미지 백업
1. delete.sh script 추가
2. deploy.yml에 ECR에 로그인 및 image push 로직 추가
3. { github.sha } 로 이미지 tagging
1. github action deploy에 실패 시 AWS ECR에 백업되어있는 이미지로 이를 재가동하는 로직을 추가하면 더 좋은 CD flow가 될 것 같습니다.
> [SO-147] feat : 사용하지 않는 docker image 삭제, AWS ECR로 백업

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
redis에 넣어지는 refreshToken과 실제 전달되는 refreshToken값이 다른 것을 확인
하위 도메인에서도 접근 가능하도록 .weddingmate.co.kr로 수정
> [SO-150] feat: RefreshToken 도메인 수정

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CookieAuthorizationRequestRepository.java
oauth2 로그인 시 param의 값을 잘 인식할 수 있도록 camel case에서 snake case로 변경
기존 redirectUrl -> redirect_uri로 변경
oauth2 로그인 시 카멜 케이스에 대한 인식을 못하는 이슈가 있어 스네이크 케이스로 변수명 변경
> [SO-150] fix: cookie param snake case로 변경

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/controller/CategoryController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FileController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/controller/TagController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/dto/ApiResponse.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/dto/ApiResponseStatus.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorResponse.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
- 프론트와의 원활한 API 통신을 위해 JSend 기반 API 공통 응답 포맷 생성
- 성공 시 status (SUCCESS) , data 형식을 리턴
- 실패 시 status (FAIL), data 형식을 리턴
- ErrorResponse도 API 응답 포맷대로 리턴하도록 GlobalExceptionHandler에서 처리했습니다.
- 현재 생성된 API에는 모두 공통 응답 포맷을 적용하였습니다.
> [SO-148] feat: API 공통 응답 포맷 생성

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/controller/CategoryController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FileController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CookieAuthorizationRequestRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/controller/TagController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtTokenProvider.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/dto/ApiResponse.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/dto/ApiResponseStatus.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorResponse.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
- 개발 과정의 번거로움을 해결하고자 AccessToken 유효 기간 변경
- 필요없는 로그 제거
1. 기존 30분이던 AccessToken 유효 기간을 일시적으로 12시간으로 변경했습니다.
2. 사용되지 않는 redirectUri 관련 log를 제거했습니다.
(서버 로그의 대부분을 차지하고 있음)
> [SO-178] feat: AccessToken 유효 기간 12시간으로 변경 및 로그 제거

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserAccountStatusEnum.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserRegisterStatusEnum.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
회원가입 상태를 확인할 수 있는 API 추가
1. 회원 가입 상태를 나타내는 UserRegisterEnum 추가 (UNREGISTERED / PLANNER / CUSTOMER)
- UNREGISTERED : OAuth2 과정을 거쳐 User가 생성되었으나 아직 플래너/예비부부 회원가입을 하지 않은 경우
- PLANNER : OAuth2 & 플래너 회원가입을 완료한 경우
- CUSTOMER : OAuth2 & 예비부부 회원가입을 완료한 경우
3. 기존 UserEnum을 UserAccountStatusEnum으로 변경
4. 회원 가입 상태 체크 API 생성
(ex. 플래너로 회원가입 한 후)
5. 회원 가입 상태 체크 관련 로직 추가
6. 기존의 중복 회원가입 관련 로직을 UserRegisterEnum을 사용하도록 리팩토링
> [SO-176] feat: 회원가입 상태 체크 API 추가

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfileController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfileFileUploadController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileUpdateReqDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileUpdateResDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/mapper/ProfileMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
기존 자기소개, sns에 더불어 프로필 태그까지 수정할 수 있도록 API 변경
> body와 응답에 tagList가 추가되었습니다.
```
{
"bio": "단 한 번뿐인 웨딩을 누구보다 아름답게, 10년 경력의 플래너입니다.",
"sns": "@oneandonlywedding",
"tagList": "열정적인, 열씨미!!"
}
```
```
{
"status": "SUCCESS",
"data": {
"bio": "단 한 번뿐인 웨딩을 누구보다 아름답게, 10년 경력의 플래너입니다.",
"sns": "@oneandonlywedding",
"tagList": "열정적인, 열씨미!!"
}
}
```
> [SO-187] feat: 플래너 프로필 태그 수정 추가

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FileUploadService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileFileUploadService.java
유저 프로필 사진을 update하는 API에서는 수정된 파일 URL이 잘 반환되나,
프로필을 조회했을 때는 변경사항이 반영되지 않는 오류 해결
1. 파일을 s3에 업로드하고 fileRepository에 저장하는 로직은 잘 작동되는 것 체크
2. 해당 파일을 user와 연결하는 로직이 빠져있어 추가
> [SO-195] fix: 유저 프로필 사진이 변경되지 않는 문제 해결

- build.gradle
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatMessageController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatRoomController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatMessageDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatMessageReqDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatMessageResDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomResDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatMessage.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatRoom.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/enums/MessageType.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/pubsub/RedisPublisher.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/pubsub/RedisSubscriber.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/repository/ChatMessageRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/repository/ChatRoomRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/service/ChatMessageService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/service/ChatRoomService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jackson/JackSonConfig.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/redis/RedisConfig.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/stomp/WebSocketConfig.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/chat/ChatRoomNotAuthorizedException.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/chat/ChatRoomNotFoundException.java
Redis sub/pub 및 Websocket을 이용하여 실시간 채팅 및 채팅방 추가
1) Redis에 sub/pub 관련 설정 추가
2) 채팅방 CRD API 추가
3) 실시간 채팅 API 추가
4) 채팅방 메시지 조회 API 추가
> 유저와 receiver로 채팅방 생성
```
{
"receiver": "CSKIM" // 받는 사람 닉네임
}
```
```
{
"status": "SUCCESS",
"data": {
"roomName": "mnjiya500@daum.net_cskim999@kakao.com",
"roomId": "1d66c126-75cc-4839-9c08-21134adeb637",
"sender": "mnjiya500@daum.net",
"receiver": "cskim999@kakao.com",
"latestMessage": "",
"lastMessageTime": "2023-09-03T17:48:40.956476"
}
}
```
> 유저가 포함된 채팅방 목록 조회
(채팅 없이 채팅방만 만들어진 경우에는 조회되지 않습니다)
```
{
"status": "SUCCESS",
"data": [
{
"roomName": "CSKIM",
"roomId": "1d66c126-75cc-4839-9c08-21134adeb637",
"sender": "mnjiya500@daum.net",
"receiver": "cskim999@kakao.com",
"latestMessage": "쮸앤밀",
"lastMessageTime": "2023-09-03T18:33:23.173679"
}
]
}
```
> 채팅방 …
> [SO-209] 채팅방 CRD & 실시간 채팅 API 추가

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerInfoDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/CustomerSignupReqDto.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customer.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/CustomerMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/PlannerMapper.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
- planner 지역 태그를 3개까지 받음에 따라 planner, 관련 dto의 region을 regionList로 변경
- customer 지역 태그를 3개까지 받음에 따라 customer, 관련 dto의 region을 regionList로 변경
아래 API에서 region -> regionList로 변경
- 플래너 회원가입 API
- 예비부부 회원가입 API
- 플래너 정보 수정 API
> [SO-232] style: planner, customer 지역 리스트 변수 이름 regionList로 변경

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfoliosMapper.java
- portfolioDetail에서 plannerProfileId 반환
1. 그동안은 포트폴리오 디테일에서 플래너 아이디를 반환 중
2. 하지만 플래너 디테일에서 요구하는 id 값은 플래너 프로필 아이디이기 때문에 이를 수정
> [SO-247] hotfix : 포트폴리오 디테일에서 플래너 프로필 아이디 반환

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/repository/FilesRepository.java
- 삭제된 아이템의 피드 이미지 제외
- files와 items를 item_id로 innerjoin 하여 items에서 is_delete가 False인 애들만 가져오게끔 변경
> [SO-248] hotfix : 삭제된 아이템의 피드 이미지 제외

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
- 기존에 redirect url이 String 값으로 메인 도메인에 할당되어 있었음
- 하지만 개발서버와 운영서버를 분리하여 이것을 변경할 필요가 있어짐
- redirect_url의 주소를 env.properties에 넣어 이를 받아오는 방식으로 변경
1. merge 전에 github secrets 변경 필요
- 쿠키에 사용하는 도메인은 host에 서브 도메인은 포함되지 않기 때문에 변경하지 않았습니다. 하지만 혹시 모르니 변경이 필요할 것 같은지 확인 부탁드려요!
> [SO-265] fix : redirect url 환경변수로 분리

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLikes.java
회원 탈퇴 기능 개발 중 is_deleted column이 DB에 생성되었으나, 관련 코드가 완성되지 않아 is_deleted 값이 초기화되지 않는 문제 발생
- entity 관련된 코드만 먼저 커밋하는 방식으로 해결
> [SO-267] fix: userlike에 is_deleted 관련 로직 추가

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/entity/Files.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Items.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/repository/ItemsRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLikes.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/enums/LikeEnum.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolios.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/PortfoliosRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/entity/PlannerProfiles.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfilesService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfilesService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customers.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planners.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/CustomersRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/PlannersRepository.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
회원 탈퇴 시 user, customer, planner, portfolio, item, like가 soft delete 되도록 설정
회원 탈퇴 시 user의 상태가 WITHDRAW로 변경되고, 연결된 객체들의 is_deleted 컬럼이 true로 변경됩니다
각 entity에는 아래처럼 조건을 걸어놓아, 삭제된 객체는 조회가 되지 않도록 설정했습니다.
entity 단에서 로직을 설정해놓았기 때문에  service로직에서 checkIsDeleted 관련 함수를 삭제했습니다.
```java
@SQLDelete(sql = "UPDATE portfolios SET is_deleted = true WHERE portfolio_id = ?")
@Where(clause = "is_deleted = false")
```
Item의 경우 지연 로딩으로 구성되어 있기 때문에 item.portfolio.user = :user 로직이 작동하지 않았습니다.
따라서 join을 사용해 item을 불러오고, 그 후에 userId와 일치하는지 체크하였습니다
사용자와 연관된 모든 아이템을 한꺼번에 논리적으로 삭제하기 때문에 쿼리가 적게 나간다는 장점이 있습니다
(fetch join을 쓰고 싶었는데 데이터 조회에만 적용할 수 있대서 그냥 일반 join으로 했습니다)
- 예를 들어 item을 클릭했는데 작성자가 이미 탈퇴한 회원이거나, 포트폴리오가 이미 삭제된 경우 프론트에게 어떤 식으로 전달해야 할 지 생각해보아야 합니다.
> [SO-141] feat: soft delete로 회원 탈퇴 구현

- .github/workflows/deploy.yml
- code deploy를 활용한 CD 파이프라인 구성
- github actions에서는 CI 역할만 하도록 분리
1. code deploy를 활용한 무중단 배포 환경 설계
2. blue green 배포 전략을 선택하기 위한 ec2 auto scaling 구성
- 현재 이미지의 태그를 latest로 축약하여 표시중인데 그 이유는 이미지 별 고유 태그를 docker-compose.yml 에 주입하는 방법을 알아내는데 실패했기 때문이다. 하지만 이는 좋지 않은 이미지 태깅 방식이기 때문에 추후 개선해야 할 사항으로 보인다.
- WeddingMate Backend Wiki에 자세한 구축 과정을 설명해두었으니 참조 바랍니다.
[CI/CD 파이프라인 구축](https://github.com/SWM-Space-Odyssey/WeddingMate_BackEnd/wiki/CI-CD-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8-%EA%B5%AC%EC%B6%95-:-Github-Actions,-CodeDeploy%E2%80%90Blue-Green-%EB%B0%B0%ED%8F%AC-%EC%A0%84%EB%9E%B5,-Auto-Scaling%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%98%EC%97%AC)
> [SO-269] feat : CodeDeploy를 활용한 CD 파이프라인 분리

- .github/workflows/deploy.yml
- appspec.yml
- config/codedeploy/beforeInstall.sh
DeploymentLimitExceededException(**The deployment failed because a specified file already exists at this location: ~**)을 해결하기 위해 beforeInstall.sh 추가
- codeDeploy에서 문제가 생겨 배포가 3단계까지 진행되지 않아(무한 로딩), 변경 사항이 배포 서버에 반영되지 않는 상태
- 이로 인해 swagger, actuator에서 401 오류 발생
`DeploymentLimitExceededException` 문제가 발생하여 github action이 실행되지 않음
따라서 지금까지는 수동으로 codeDeploy에 이미 돌아가고 있는 이미지를 중지하고 매번 다시 실행시켜야 했음
- 이미 파일이 존재할 경우 삭제 후 진행할 수도 있고, overwrite도 가능했는데 1번 방법이 정석이라 그것으로 진행
- appspec.yml의 hook에 beforeInstall 추가
> [SO-288] fix: codedeploy 스크립트 수정

- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/KakaoOAuth2User.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/OAuth2UserInfo.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomOAuth2UserService.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserAccountStatusEnum.java
- src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
악성 유저를 거르기 위해 카카오 회원가입 및 로그인 시 gender와 age로 검증
- 악성 유저들의 무분별한 가입을 막기 위해 카카오에서 성별, 연령대를 받아 거르기로 함
- 연령대가 20~29, 30~39가 아닌 경우나 성별, 연령대를 허용하지 않은 경우는 user 상태가 NON_ELIGIBLE로 들어감
- 해당 유저가 로그인을 다시 시도할 경우 프론트엔드에서 해당하는 error page로 redirect되도록 설정
- 기존 유저들의 가입 및 접근을 유지하기 위해 gender와 age는 각각 female, 20~29로 변경함
> [SO-298] feat: 카카오 로그인 시 gender와 age 추가

- src/main/resources/application-oauth.yml
카카오 인가 코드 요청 과정에서 성별, 연령대 요청하도록 설정
> [SO-301] fix: oauth.yml에 성별, 연령대 추가
