SWM-Space-Odyssey/WeddingMate_BackEnd

src/main/java/swmaestro/spaceodyssey/weddingmate/WeddingmateApplication.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/entity/BaseTimeEntity.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/ErrorCode.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/ErrorResponse.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/GlobalExceptionHandler.java
프로젝트 폴더 구조 세팅
- global / domain으로 구분
- global에 error 관련 class 생성
- baseTimeEntity 생성 및 적용
- 추후에 jsend 형식 관련해서 error 형식을 재정비해야 할 것 같습니다.
=> Feature/so 26 프로젝트 폴더구조 세팅

.github/workflows/deploy.yml, Dockerfile, config/nginx/Dockerfile, config/nginx/nginx.conf, config/scripts/deploy.sh, docker-compose.prod.yml, docker-compose.yml, src/main/resources/application.yml
CI/CD를 위한 docker, docker-compose, nignx, github actions 설정
1. github actions workflow에 deploy.yml 추가
2. config/scripts/deploy.sh 파일 추가
3. config/scripts/nginx 폴더에 nginx 관련 설정 추가
4. docker-compose up 명령어로 web, nginx 컨테이너 구동
5. github actions secrets에 환경변수, AWS host/key 등록
1. docker image 및 container 삭제 flow 추가
- 안하면 ec2 용량 문제 발생
2. AWS ECR 혹은 docker-hub 에 이미지 업로드 flow 추가
- 배포 안정성을 위해 이미지 백업
=> feat : Feature/so-30 배포 자동화 flow 추가

.github/workflows/deploy.yml, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
- https 적용을 완료한 도메인으로 kakao login redirect url을 변경
1. 새로 구입한 도메인으로 서버와 클라이언트 도메인을 맞췄지만 여전히 cookie가 set 되지 않음
2. set-cookie가 https이 적용된 도메인에서만 작동한다고 함. 따라서 https가 적용된 도메인으로 다시 테스트해 볼 예정
=> [SO-143] chore : https 적용 도메인으로 redirect url 변경

.github/workflows/add_review_label_on_open.yml, .github/workflows/remove_labels_on_close.yml
- PR open 시 자동으로 `👀리뷰필요` 라벨 추가
- PR close 시 리뷰 진행 관련 라벨은 제거
- PR open 시 자동으로 `👀리뷰필요` 라벨 추가
- PR close 시 리뷰 진행 관련 라벨은 제거. 아래 라벨만 남도록 합니다.
`  LABELS_TO_KEEP=("bugs" "documentation" "🐇Simple" "🚨긴급" "🛠refactor")`
- 라벨에 이모티콘이 포함되어 있어서 인코딩 처리를 했습니다.
=> [SO-185] feat: PR 라벨 추가 및 삭제 workflow 추가

.github/workflows/add_review_label_on_open.yml, .github/workflows/remove_labels_on_close.yml
=> [SO-185] feat: workflow 체크용 PR

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Item.java
- 중복되어 작성되어 있던 setLikeCount 함수 제거
=> [SO-228] hotfix : likecount setter 중복 제거

.github/workflows/deploy.yml, config/scripts/deploy.sh
- 현재 ecr에 이미지를 push 하고 있어 aws credentials를 이용하는데 이와 관련된 배포 오류 발생
- 현재 ecr에 push된 이미지들을 사용하고 있지 않으므로 이를 제거하는 것이 나을 것이라고 판단함
- 따라서 배포 로직에 ecr 관련 부분 삭제
=> [SO-244] hotfix : ecr 관련 로직 제거

.github/deploy_prod.yml, .github/workflows/deploy_prod.yml
- 배포 서버 github actions 워크플로우 추가
1. 배포 서버는 main branch와 연결
2. 안정적인 인스턴스를 위해 t2.medium, storage는 30GB로 선택
3. 도메인은 server.weddingmate.co.kr
=> [SO-200] feat : 배포 서버 github actions 워크플로우 추가

.github/workflows/deploy_prod.yml
- 운영 서버에 필요한 환경변수들을 github secrets 상에서 분리한 뒤 이를 workflow에도 반영
=> [SO-200] fix : 운영 서버 환경변수 분리

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
- import 구문을 빼먹어 에러 발생
- Value import 구문 추가
=> [SO-265] hotfix : import 구문 추가

.github/workflows/deploy.yml, Dockerfile, appspec.yml, build.gradle, config/scripts/deploy.sh, docker-compose.prod.yml
1. 기존 로직대로 ec2 내에서 docker-compose로 이미지를 gradle build 시 무한로딩 오류 발생
1. ec2 용량 부족에 따른 문제
2. 현재 우리 서버는 t2.micro 를 사용중이지만 이미 20GB로 증설해놓은 상태이기 때문에 용량을 더 늘리는 것은 무리라고 판단
3. [관련 블로그](https://ksh-coding.tistory.com/40)
2. image를 ecr에 push 하고 이를 pull 받아와 구동시키는 것으로 해결
3. deploy시 health check에 자꾸 fail 하는 문제가 발생하여 spring actuator dependency 추가
4. github actions build 결과를 slack에 notify 해주는 로직 추가
- docker image github actions 에서 build 후 ecr에 push 하는 로직 추가
- scripts/deploy.sh에서 ecr에 올린 이미지 pull 후 docker.compose.prod.yml에서 이를 기반으로 컨테이너 구동
- aws 상태검사 url 변경(actuator/health)
=> [SO-270] hotfix : docker image ecr에 pull/push 로직 추가

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/service/ChatRoomsService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/service/CompaniesRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/repository/FilesRepository.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FilesRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FilesService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/ImageFilesValidator.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/repository/LikesRepository.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfilesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/repository/PlannerProfilesRepository.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/CustomerProfilesService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfilesFilesUploadService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/AuthService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/CustomersService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/PlannersService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/CustomersRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/PlannersRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/UsersRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtAuthenticationFilter.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtTokenProvider.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/utils/CookieUtils.java
순환 참조를 피하기 위핸 `RepositoryService` 도입
- 비즈니스 로직을 처리하기 위해 서비스 계층을 설계
- 안재홍 멘토님의 조언에 따라 @Transactional을 이용해 repository 접근을 제어하기 위해 서비스 단에서 repository 접근 로직 추가
```java
/*================== Repository 접근 ==================*/
@Transactional
public Planners findPlannerByUser(Users users) {
return plannersRepository.findByUsers(users)
.orElseThrow(PlannerNotFoundException::new);
}
@Transactional
public Planners findPlannerByPlannerProfileId(Long plannerProfileId){
return plannersRepository.findByPlannerProfiles_PlannerProfileId(plannerProfileId)
.orElseThrow(PlannerNotFoundException::new);
}
```
개발을 진행하면서 한 서비스에서 다른 서비스의 repository 접근 로직을 사용해야 하는 일이 점점 잦아졌고, 그 결과 순환 참조가 종종 발생하곤 했습니다.
따라서 이를 피하기 위해 다른 서비스의 repository 메서드를 직접 호출하는 일이 빈번하게 발생했습니다.
```java
@Service
public class UserService { …
```
=> [SO-271] refactor: 순환 참조를 피하기 위해 service 계층에서 repository 관련 로직 분리

build.gradle, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatMessagesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatRoomsController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomDto.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomResDto.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatMessages.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatRooms.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FilesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/entity/Files.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemsController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemsFilesUploadController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfoliosController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/CustomerProfilesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfilesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfilesFilesUploadController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfilesController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customers.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/swagger/SwaggerConfig.java, src/main/resources/application-swagger.yml, src/main/resources/application.yml
- swagger 추가
- swagger 관련 의존성 및 설정파일 추가
- 각 controller에 swagger tag 추가
찾아보니까 grouping, schema 설정 등 다양하게 할 수 있는 것 같습니다~!
현재는 controller가 아닌 entity나 dto도 인식해서 자동으로 api를 만들어주는 것 같은데 관련해서 해결 방안 찾아보겠습니다 <br>
=> [SO-273] feat: Springdoc을 이용한 swagger 추가

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/KakaoOAuth2User.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/OAuth2UserInfo.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomOAuth2UserService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserAccountStatusEnum.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
Reverts SWM-Space-Odyssey/WeddingMate_BackEnd#133
=> Revert "[SO-298] feat: 카카오 로그인 시 gender와 age 추가"

.github/workflows/deploy_prod.yml
=> [SO-300] hotfix : ecr repository명 수정

.github/workflows/deploy_prod.yml
- 배포한 v2 버전의 운영서버 ECR 레포지토리 명 hotfix
=> hotfix : v2 관련 hotfix 반영(#138)

src/main/resources/application-oauth.yml
- 카카오톡 성별, 연령대 추가
- application-oauth.yml 변경
=> [SO-301] feat: 성별, 연령대 추가 (#140)

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/controller/CompanyController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/dto/CompanyItemResDto.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/dto/CompanyResDto.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/mapper/CompanyMapper.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/service/CompaniesService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java, src/test/java/swmaestro/spaceodyssey/weddingmate/domain/company/controller/CompanyControllerTest.java
- 업체 디테일 페이지 구현
- 디자인과 같이 이미지 최대 개수 9개, 리뷰  최대 개수 2개로 설정
- 통합 테스트코드 추가
=> [SO-256] feat : 업체 조회 api 구현

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/controller/CompanyController.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/dto/CompanySearchResDto.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/mapper/CompanyMapper.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/repository/CompaniesRepository.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/service/CompaniesRepositoryService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/service/CompaniesService.java
- 업체 검색 API 구현
- MySQL Full Text Search를 사용하여 name, category 칼럼 검색
1. 업체 검색 API full text search를 활용하여 구현
2. builder 패턴을 활용하여 객체 생성하는 로직을 dto 내부에 존재하도록 refactor
=> [SO-312] feat : 업체 검색 API 구현

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/community/comment/service/CommentService.java, src/main/java/swmaestro/spaceodyssey/weddingmate/domain/community/post/entity/Posts.java
- 댓글 삭제 시 commentCount 감소X
- 감소하도록 수정
=> [SO-311] fix : 댓글 삭제 시 감소 로직 추가

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/community/post/controller/PostsController.java
- post list가 최신순이 아닌 오래된 순으로 정렬되는 문제 발생
- Pageable 객체를 직접 생성하여 sort 옵션 추가
=> [SO-311] fix : post list 최신 순으로 변경

src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/dto/CompanySearchResDto.java
- No serializer found for class 오류 발생
- CompanySearchResDto에 getter 추가
- 스프링 부트의 Jackson 라이브러리가 탑재(?)되어있음
- Serialize 하는 과정에서 접근 제한자가 public이거나 Getter/Setter를 이용하기 때문에 필드가 private로 선언되어있어 JSON 변환 과정에서 문제가 발생
[stackoverflow](https://stackoverflow.com/questions/59578802/jackson-no-serializer-found-for-class-and-no-properties-discovered-to-cre)
=> [SO-312] fix : CompanySearchResDto에 getter 추가
